var datafriends = [
    "北京您好|101","北京印象|102","北京公交|103","北京天气","北京新闻",
	"李昂达","李乐乐","李伟",
	"马彦龙","马凯","马建安","马璐璐",
	"朱宏","朱一平","朱北方","朱若楠","朱佳燕",
	"Aberdeen", "Ada", "Adamsville", "Addyston", "Adelphi", "Adena", "Adrian", "Akron",
	"Barberton", "Barlow", "Barnesville", "Bartlett", "Barton", "Bascom", "Batavia",
	"Caldwell", "Caledonia", "Cambridge", "Camden", "Cameron", "Camp Dennison",
	"Dayton", "De Graff", "Decatur", "Deerfield", "Deersville", "Defiance",
	"East Liberty", "East Liverpool", "East Palestine", "East Rochester",
	"Empire", "Englewood", "Enon", "Etna", "Euclid", "Evansport", "Fairborn",
	"Fairfield", "Fairpoint", "Fairview", "Farmdale", "Farmer", "Farmersville",
	"Galena", "Galion", "Gallipolis", "Galloway", "Gambier", "Garrettsville",
	"Gates Mills", "Geneva", "Genoa", "Georgetown", "Germantown", "Gettysburg",
	"Hamden", "Hamersville", "Hamilton", "Hamler", "Hammondsville",
	"Irondale", "Ironton", "Irwin", "Isle Saint George", "Jackson", "Jackson Center",
	"Kansas", "Keene", "Kelleys Island", "Kensington", "Kent", "Kenton",
	"Kerr", "Kettlersville", "Kidron", "Kilbourne", "Killbuck", "Kimbolton",
	"Lafayette", "Lafferty", "Lagrange", "Laings", "Lake Milton", "Lakemore",
	"Lyons", "Macedonia", "Macksburg", "Madison", "Magnetic Springs",
	"Magnolia", "Maineville", "Malaga", "Malinta", "Malta", "Malvern",
	"Manchester", "Mansfield", "Mantua", "Maple Heights", "Maplewood",
	"Marathon", "Marengo", "Maria Stein", "Marietta", "Marion",
	"New Paris", "New Philadelphia", "New Plymouth", "New Richmond",
	"Oberlin", "Oceola", "Ohio City", "Okeana", "Okolona", "Old Fort",
	"Old Washington", "Olmsted Falls", "Ontario", "Orangeville",
	"Paris", "Parkman", "Pataskala", "Patriot", "Paulding", "Payne",
	"Quaker City", "Quincy", "Racine", "Radnor", "Randolph", "Rarden",
	"Ravenna", "Rawson", "Ray", "Rayland", "Raymond", "Reedsville",
	"Saint Louisville", "Saint Marys", "Saint Paris", "Salem", "Salesville",
	"Salineville", "Sandusky", "Sandyville", "Sarahsville", "Sardinia",
	"Terrace Park", "The Plains", "Thompson", "Thornville", "Thurman",
	"Thurston", "Tiffin", "Tiltonsville", "Tipp City", "Tippecanoe", "Tiro",
	"Uhrichsville", "Union City", "Union Furnace", "Unionport", "Uniontown",
	"Unionville", "Unionville Center", "Uniopolis", "Upper Sandusky", "Urbana",
	"Utica", "Valley City", "Van Buren", "Van Wert", "Vandalia", "Vanlue",
	"Vaughnsville", "Venedocia", "Vermilion", "Verona", "Versailles",
	"Vickery", "Vienna", "Vincent", "Vinton", "Wadsworth", "Wakefield",
	"Wakeman", "Walbridge", "Waldo", "Walhonding", "Walnut Creek", "Wapakoneta",
	"Warnock", "Warren", "Warsaw", "Washington Court House",
	"Yorkshire", "Yorkville", "Youngstown", "Zaleski", "Zanesfield", "Zanesville",
	"Zoar"
];